// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	article "github.com/foodi-org/foodi-user-proxy/internal/handler/article"
	login "github.com/foodi-org/foodi-user-proxy/internal/handler/login"
	user "github.com/foodi-org/foodi-user-proxy/internal/handler/user"
	"github.com/foodi-org/foodi-user-proxy/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 发布文章
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: article.ArticleActionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// user login
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: login.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户基础信息
				Method:  http.MethodGet,
				Path:    "/baseInfo",
				Handler: user.UserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
